apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-psql
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard