# sonarqube-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /opt/sonarqube/data && chmod -R 755 /opt/sonarqube/data"]
          volumeMounts:
            - name: sonarqube-storage
              mountPath: /opt/sonarqube/data
      containers:
        - name: sonarqube
          image: sonarqube:9.9-community
          env:
            - name: SONAR_JDBC_URL
              value: jdbc:postgresql://psql-svc:5432/sonarqube
            - name: SONAR_JDBC_USERNAME
              value: sonar
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: sonarqube-storage
              mountPath: /opt/sonarqube/data
      volumes:
        - name: sonarqube-storage
          persistentVolumeClaim:
            claimName: pvc-sonar

